### PR TITLE
Added Support for 1.20.5 and 1.20.6

### PR DESCRIPTION
**Pull request by Kici33**

### CODE REVIEW

**Comment by resi23** [comment]
Works on Spigot but not on Paper. Paper has changed things with the craftbukkit package. Why the version query in this plugin no longer works.

`papertestserver  | [09:32:19 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'images-2.3.3.jar' in folder 'plugins/.paper-remapped'
papertestserver  | org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
papertestserver  |      at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
papertestserver  | Caused by: java.lang.ExceptionInInitializerError
papertestserver  |      at images-2.3.3.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images-2.3.3.jar:?]
papertestserver  |      at images-2.3.3.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images-2.3.3.jar:?]
papertestserver  |      at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
papertestserver  |      at java.base/java.lang.Class.forName(Unknown Source) ~[?:?]
papertestserver  |      at java.base/java.lang.Class.forName(Unknown Source) ~[?:?]
papertestserver  |      at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
papertestserver  |      at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      ... 9 more
papertestserver  | Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, -1) out of bounds for length 22
papertestserver  |      at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source) ~[?:?]
papertestserver  |      at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source) ~[?:?]
papertestserver  |      at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source) ~[?:?]
papertestserver  |      at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source) ~[?:?]
papertestserver  |      at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
papertestserver  |      at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source) ~[?:?]
papertestserver  |      at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source) ~[?:?]
papertestserver  |      at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source) ~[?:?]
papertestserver  |      at java.base/java.lang.String.substring(Unknown Source) ~[?:?]
papertestserver  |      at images-2.3.3.jar/com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:170) ~[images-2.3.3.jar:?]
papertestserver  |      at images-2.3.3.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images-2.3.3.jar:?]
papertestserver  |      at images-2.3.3.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images-2.3.3.jar:?]
papertestserver  |      at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
papertestserver  |      at java.base/java.lang.Class.forName(Unknown Source) ~[?:?]
papertestserver  |      at java.base/java.lang.Class.forName(Unknown Source) ~[?:?]
papertestserver  |      at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
papertestserver  |      at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:1.20.6-90-b149584]
papertestserver  |      ... 9 more`

**Comment by resi23** [comment]
OK. So this PR works on 1.20.6 on Spigot but not on Paper because Paper removed the Craftbukkit relocation. This leads to the error that the Minecraft version cannot be parsed. Because you posted https://github.com/Andavin/Images/issues/84

**Comment by lowercasebtw** [comment]
bump

**Comment by resi23** [comment]
> bump

https://github.com/resi23/Images/releases/tag/v2.3.3

**Comment by resi23** [comment]
only this https://github.com/resi23/Images/releases/tag/v2.3.4-PaperFix

**Comment by Andavin** [comment]
Thank you for the PR! I believe this is taken care of.

**Pull request closed without merging**
