### PR TITLE
Added Support for 1.20.5 and 1.20.6

### PR DESCRIPTION
**Pull request by Kici33**
Changed version from `2.3.2` to `2.3.3`
Added Support for 1.20.5 and 1.20.6
Updated specialsource-maven-plugin so it can utilize Java 21 when remapping the server files

### CODE REVIEW

**Comment by CloudeLecaw** [comment]
im confused.. the plgin version was allready 2.4.0...

**Comment by resi23** [comment]
> im confused.. the plgin version was allready 2.4.0...

Now I'm confused on the Spigot site the 2.3.2 is the latest
https://www.spigotmc.org/resources/custom-images.53036/

**Comment by CloudeLecaw** [comment]
we didnt used the spigot version we use the vesion from the github that is marked as 2.4.0

**Comment by resi23** [comment]
But here it is only 2.3.2 o.O

**Comment by resi23** [comment]
OK. So this PR works on 1.20.6 on Spigot but not on Paper because Paper removed the Craftbukkit relocation. This leads to the error that the Minecraft version cannot be parsed. Because you posted https://github.com/Andavin/Images/issues/84

**Comment by CloudeLecaw** [comment]
image
i just see both have different size.. i  wish i could renember who was giving away this 2.4.0 version
so there are differences between these?

**Comment by resi23** [comment]
The 2.3.2 is the one from the Spigot site? This Build don't have include this PR. The difference of 11 KB is explained by the package for 1.20.5/6. My version is 291 KB too.
Bild_2024-05-23_110256408

**Comment by resi23** [comment]
I found it. Andavin put it in the [Spigot MC Discussion](https://www.spigotmc.org/threads/custom-images.302109/)Thread](https://www.spigotmc.org/threads/custom-images.302109/page-33#post-4727413) wow

**Pull request closed without merging**
