### PR TITLE
Add support for 1.20.4

### PR DESCRIPTION
**Pull request by resi23**
As the title suggests, the PR supports version 1.20.4. Hope the version is ok this time ;)

### CODE REVIEW

**Comment by LucidAPs** [comment]
> As the title suggests, the PR supports version 1.20.4. Hope the version is ok this time ;)

Hey, can you give us a build just for until the plugin is officially updated.

**Comment by resi23** [comment]
> > As the title suggests, the PR supports version 1.20.4. Hope the version is ok this time ;)
> 
> Hey, can you give us a build just for until the plugin is officially updated.

https://github.com/resi23/Images

**Comment by CloudeLecaw** [comment]
> > As the title suggests, the PR supports version 1.20.4. Hope the version is ok this time ;)
> 
> Hey, can you give us a build just for until the plugin is officially updated.

https://github.com/resi23/Images/releases/download/2.3.2/images-2.3.2.jar

**Review by Andavin — APPROVED** [review]
This looks great! Tested it and I don't see any issues either.

Thanks for submitting it

**Pull request merged**
