### PR TITLE
Update to 2.3.0 with support for 1.20

### PR DESCRIPTION
**Pull request by resi23**
tested with spigot and paper 1.20

### CODE REVIEW

**Review by Andavin — APPROVED** [review]
Thanks for the contribution!

One note is that I don't normally like to increment the feature number for a simple version addition, however, since I also merged another PR with a feature I will aloow this one to increment to 2.3.0 instead of 2.2.10.

Note that you missed a typo in the MinecraftVersion class, but I'll go ahead and fix that along with changing the version to 1.20.1 support.

Thanks again!

**Comment by resi23** [comment]
Entschuldigung für den Versionsfehler. Das nächste Mal werde ich es richtig machen :)

**Comment by Louitic** [comment]
I run a bedrock/java server, and on java it's fine but on the bedrock version the images have a item frame background.

**Comment by CloudeLecaw** [comment]
well images never was official supporting bedrock
so if your see strange things  on bedrock clients but not on java clients then its not really a problem of the plugin to solve this.

**Pull request merged**
